// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package models

// GetDataParams defines parameters for GetData.
type GetDataParams struct {
	V            string  `form:"v" json:"v"`
	UserId       string  `form:"user_id" json:"user_id"`
	InMedal      int     `form:"in_medal" json:"in_medal"`
	OutMedal     int     `form:"out_medal" json:"out_medal"`
	SlotHit      int     `form:"slot_hit" json:"slot_hit"`
	GetShirbe    int     `form:"get_shirbe" json:"get_shirbe"`
	StartSlot    int     `form:"start_slot" json:"start_slot"`
	ShirbeBuy300 int     `form:"shirbe_buy300" json:"shirbe_buy300"`
	Medal1       int     `form:"medal_1" json:"medal_1"`
	Medal2       int     `form:"medal_2" json:"medal_2"`
	Medal3       int     `form:"medal_3" json:"medal_3"`
	Medal4       int     `form:"medal_4" json:"medal_4"`
	Medal5       int     `form:"medal_5" json:"medal_5"`
	RMedal       int     `form:"R_medal" json:"R_medal"`
	Second       float32 `form:"second" json:"second"`
	Minute       int     `form:"minute" json:"minute"`
	Hour         int     `form:"hour" json:"hour"`

	// Sig HMAC-SHA256署名（順序固定・user_id込みで生成）
	Sig string `form:"sig" json:"sig"`
}
