// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package models

import (
	"time"
)

// Defines values for GetRankingsParamsSort.
const (
	Fever           GetRankingsParamsSort = "fever"
	HaveMedal       GetRankingsParamsSort = "have_medal"
	InMedal         GetRankingsParamsSort = "in_medal"
	MaxChainItem    GetRankingsParamsSort = "max_chain_item"
	MaxChainOrange  GetRankingsParamsSort = "max_chain_orange"
	MaxChainRainbow GetRankingsParamsSort = "max_chain_rainbow"
	OutMedal        GetRankingsParamsSort = "out_medal"
)

// AchievementRates defines model for AchievementRates.
type AchievementRates struct {
	// AchievementRates 実績IDごとの取得率データ
	AchievementRates *map[string]struct {
		// Count この実績を取得したユーザー数
		Count *int `json:"count,omitempty"`

		// Rate 取得率（0.0-1.0）
		Rate *float32 `json:"rate,omitempty"`
	} `json:"achievement_rates,omitempty"`

	// TotalUsers 総ユーザー数
	TotalUsers *int `json:"total_users,omitempty"`
}

// GameData defines model for GameData.
type GameData struct {
	RMedal           *int       `db:"R_medal" json:"R_medal,omitempty"`
	CreatedAt        *time.Time `db:"created_at" json:"created_at,omitempty"`
	Fever            *int       `json:"fever,omitempty"`
	GetShirbe        *int       `db:"get_shirbe" json:"get_shirbe,omitempty"`
	HaveMedal        *int       `db:"have_medal" json:"have_medal,omitempty"`
	Id               *string    `json:"id,omitempty"`
	InMedal          *int       `db:"in_medal" json:"in_medal,omitempty"`
	Jackpots         *int       `db:"jackpots" json:"jackpots,omitempty"`
	MaxChainItem     *int       `db:"max_chain_item" json:"max_chain_item,omitempty"`
	MaxChainOrange   *int       `db:"max_chain_orange" json:"max_chain_orange,omitempty"`
	MaxChainRainbow  *int       `db:"max_chain_rainbow" json:"max_chain_rainbow,omitempty"`
	MaxJackpotWin    *int       `db:"max_jackpot_win" json:"max_jackpot_win,omitempty"`
	MaxTotalJackpot  *int       `db:"max_total_jackpot" json:"max_total_jackpot,omitempty"`
	MaxTotalUltimate *int       `db:"max_total_ultimate" json:"max_total_ultimate,omitempty"`
	Medal1           *int       `db:"medal_1" json:"medal_1,omitempty"`
	Medal2           *int       `db:"medal_2" json:"medal_2,omitempty"`
	Medal3           *int       `db:"medal_3" json:"medal_3,omitempty"`
	Medal4           *int       `db:"medal_4" json:"medal_4,omitempty"`
	Medal5           *int       `db:"medal_5" json:"medal_5,omitempty"`
	OutMedal         *int       `db:"out_medal" json:"out_medal,omitempty"`
	ShirbeBuy300     *int       `db:"shirbe_buy300" json:"shirbe_buy300,omitempty"`
	SlotHit          *int       `db:"slot_hit" json:"slot_hit,omitempty"`
	StartSlot        *int       `db:"start_slot" json:"start_slot,omitempty"`
	SugorokuSteps    *int       `db:"sugoroku_steps" json:"sugoroku_steps,omitempty"`
	TotalPlayTime    *int       `db:"total_play_time" json:"total_play_time,omitempty"`
	UserId           *string    `db:"user_id" json:"user_id,omitempty"`
	Version          *int       `json:"version,omitempty"`
}

// RankingEntry defines model for RankingEntry.
type RankingEntry struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UserId    *string    `json:"user_id,omitempty"`
	Value     *int64     `json:"value,omitempty"`
}

// SaveDataV2 defines model for SaveDataV2.
type SaveDataV2 struct {
	BallChain         *int              `db:"ball_chain" json:"ball_chain,omitempty"`
	BallGet           *int64            `db:"ball_get" json:"ball_get,omitempty"`
	Bbox              *float64          `db:"blackbox" json:"bbox,omitempty"`
	BboxAll           *float64          `db:"blackbox_total" json:"bbox_all,omitempty"`
	BstpRwd           *int              `db:"bstp_rwd" json:"bstp_rwd,omitempty"`
	BstpStep          *int              `db:"bstp_step" json:"bstp_step,omitempty"`
	BuyShbi           *int              `db:"buy_shbi" json:"buy_shbi,omitempty"`
	BuyTotal          *int              `db:"buy_total" json:"buy_total,omitempty"`
	CpmMax            *float64          `db:"cpm_max" json:"cpm_max,omitempty"`
	Credit            *int64            `db:"credit" json:"credit,omitempty"`
	CreditAll         *int64            `db:"credit_all" json:"credit_all,omitempty"`
	DcBallChain       *map[string]int   `json:"dc_ball_chain,omitempty" table:"save_data_v2_ball_chain"`
	DcBallGet         *map[string]int64 `json:"dc_ball_get,omitempty" table:"save_data_v2_ball_get"`
	DcMedalGet        *map[string]int   `json:"dc_medal_get,omitempty" table:"save_data_v2_medal_get"`
	DcPalballGet      *map[string]int   `json:"dc_palball_get,omitempty" table:"save_data_v2_palball_get"`
	DcPalballJp       *map[string]int   `json:"dc_palball_jp,omitempty" table:"save_data_v2_palball_jp"`
	Firstboot         *string           `json:"firstboot,omitempty"`
	HideRecord        *int              `db:"hide_record" json:"hide_record,omitempty"`
	JackGet           *int              `db:"jack_get" json:"jack_get,omitempty"`
	JackStartmax      *int64            `db:"jack_startmax" json:"jack_startmax,omitempty"`
	JackTotalmax      *int              `db:"jack_totalmax" json:"jack_totalmax,omitempty"`
	JackTotalmaxV2    *int64            `db:"jack_totalmax_v2" json:"jack_totalmax_v2,omitempty"`
	JackspGetAll      *float64          `db:"jacksp_get_all" json:"jacksp_get_all,omitempty"`
	JackspGetT0       *float64          `db:"jacksp_get_t0" json:"jacksp_get_t0,omitempty"`
	JackspGetT1       *float64          `db:"jacksp_get_t1" json:"jacksp_get_t1,omitempty"`
	JackspGetT2       *float64          `db:"jacksp_get_t2" json:"jacksp_get_t2,omitempty"`
	JackspGetT3       *float64          `db:"jacksp_get_t3" json:"jacksp_get_t3,omitempty"`
	JackspGetT4       *float64          `db:"jacksp_get_t4" json:"jacksp_get_t4,omitempty"`
	JackspStartmax    *float64          `db:"jacksp_startmax" json:"jacksp_startmax,omitempty"`
	JackspTotalmax    *float64          `db:"jacksp_totalmax" json:"jacksp_totalmax,omitempty"`
	LAchieve          *[]string         `json:"l_achieve,omitempty" table:"save_data_v2_achievements"`
	LPerks            *[]int            `json:"l_perks,omitempty" table:"save_data_v2_perks"`
	LPerksCredit      *[]int64          `json:"l_perks_credit,omitempty" table:"save_data_v2_perks_credit"`
	LTotems           *[]int            `json:"l_totems,omitempty" table:"save_data_v2_totems"`
	LTotemsCredit     *[]int64          `json:"l_totems_credit,omitempty" table:"save_data_v2_totems_credit"`
	LTotemsSet        *[]int            `json:"l_totems_set,omitempty" table:"save_data_v2_totems_placement"`
	Lastsave          *string           `json:"lastsave,omitempty"`
	Legacy            *int              `db:"legacy" json:"legacy,omitempty"`
	MedalGet          *int64            `db:"medal_get" json:"medal_get,omitempty"`
	MedalIn           *int              `db:"medal_in" json:"medal_in,omitempty"`
	PalballGet        *float64          `db:"palball_get" json:"palball_get,omitempty"`
	PallotLotT0       *float64          `db:"pallot_lot_t0" json:"pallot_lot_t0,omitempty"`
	PallotLotT1       *float64          `db:"pallot_lot_t1" json:"pallot_lot_t1,omitempty"`
	PallotLotT2       *float64          `db:"pallot_lot_t2" json:"pallot_lot_t2,omitempty"`
	PallotLotT3       *float64          `db:"pallot_lot_t3" json:"pallot_lot_t3,omitempty"`
	PallotLotT4       *float64          `db:"pallot_lot_t4" json:"pallot_lot_t4,omitempty"`
	Playtime          *int64            `json:"playtime,omitempty"`
	RmshbiGet         *int              `db:"rmshbi_get" json:"rmshbi_get,omitempty"`
	SlotGetfev        *int64            `db:"slot_getfev" json:"slot_getfev,omitempty"`
	SlotHit           *int64            `db:"slot_hit" json:"slot_hit,omitempty"`
	SlotStart         *int64            `db:"slot_start" json:"slot_start,omitempty"`
	SlotStartfev      *int64            `db:"slot_startfev" json:"slot_startfev,omitempty"`
	Sp                *float64          `db:"skill_point" json:"sp,omitempty"`
	SpUse             *int              `db:"sp_use" json:"sp_use,omitempty"`
	SqrGet            *int              `db:"sqr_get" json:"sqr_get,omitempty"`
	SqrStep           *int64            `db:"sqr_step" json:"sqr_step,omitempty"`
	TaskCnt           *float64          `db:"task_cnt" json:"task_cnt,omitempty"`
	TotemAltars       *int              `db:"totem_altars" json:"totem_altars,omitempty"`
	TotemAltarsCredit *int64            `db:"totem_altars_credit" json:"totem_altars_credit,omitempty"`
	UltCombomax       *int              `db:"ult_combomax" json:"ult_combomax,omitempty"`
	UltGet            *int              `db:"ult_get" json:"ult_get,omitempty"`
	UltTotalmax       *int              `db:"ult_totalmax" json:"ult_totalmax,omitempty"`
	UltTotalmaxV2     *int64            `db:"ult_totalmax_v2" json:"ult_totalmax_v2,omitempty"`
	Version           *int              `db:"version" json:"version,omitempty"`
}

// StatisticsV2 defines model for StatisticsV2.
type StatisticsV2 struct {
	MaxChainOrange  *[]RankingEntry `json:"max_chain_orange,omitempty"`
	MaxChainRainbow *[]RankingEntry `json:"max_chain_rainbow,omitempty"`
	MaxTotalJackpot *[]RankingEntry `json:"max_total_jackpot,omitempty"`
	TotalMedals     *int            `json:"total_medals,omitempty"`
}

// StatisticsV3 defines model for StatisticsV3.
type StatisticsV3 struct {
	AchievementsCount *[]RankingEntry `json:"achievements_count,omitempty"`
	BuyShbi           *[]RankingEntry `json:"buy_shbi,omitempty"`
	CpmMax            *[]RankingEntry `json:"cpm_max,omitempty"`
	GoldenPalballGet  *[]RankingEntry `json:"golden_palball_get,omitempty"`
	JackStartmax      *[]RankingEntry `json:"jack_startmax,omitempty"`
	JackTotalmax      *[]RankingEntry `json:"jack_totalmax,omitempty"`
	JackTotalmaxV2    *[]RankingEntry `json:"jack_totalmax_v2,omitempty"`
	JackspStartmax    *[]RankingEntry `json:"jacksp_startmax,omitempty"`
	MaxChainOrange    *[]RankingEntry `json:"max_chain_orange,omitempty"`
	MaxChainRainbow   *[]RankingEntry `json:"max_chain_rainbow,omitempty"`
	SpUse             *[]RankingEntry `json:"sp_use,omitempty"`
	TotalMedals       *int            `json:"total_medals,omitempty"`
	UltCombomax       *[]RankingEntry `json:"ult_combomax,omitempty"`
	UltTotalmax       *[]RankingEntry `json:"ult_totalmax,omitempty"`
	UltTotalmaxV2     *[]RankingEntry `json:"ult_totalmax_v2,omitempty"`
}

// StatisticsV4 defines model for StatisticsV4.
type StatisticsV4 struct {
	AchievementsCount *[]RankingEntry `json:"achievements_count,omitempty"`
	BlackboxTotal     *[]RankingEntry `json:"blackbox_total,omitempty"`
	CpmMax            *[]RankingEntry `json:"cpm_max,omitempty"`
	GoldenPalballGet  *[]RankingEntry `json:"golden_palball_get,omitempty"`
	JackTotalmaxV2    *[]RankingEntry `json:"jack_totalmax_v2,omitempty"`
	JackspStartmax    *[]RankingEntry `json:"jacksp_startmax,omitempty"`
	MaxChainRainbow   *[]RankingEntry `json:"max_chain_rainbow,omitempty"`
	SpUse             *[]RankingEntry `json:"sp_use,omitempty"`

	// TotalMedals 全ユーザーのメダル合計
	TotalMedals   *int            `json:"total_medals,omitempty"`
	UltCombomax   *[]RankingEntry `json:"ult_combomax,omitempty"`
	UltTotalmaxV2 *[]RankingEntry `json:"ult_totalmax_v2,omitempty"`
}

// GetDataParams defines parameters for GetData.
type GetDataParams struct {
	Version       int    `form:"version" json:"version"`
	UserId        string `form:"user_id" json:"user_id"`
	HaveMedal     int    `form:"have_medal" json:"have_medal"`
	InMedal       int    `form:"in_medal" json:"in_medal"`
	OutMedal      int    `form:"out_medal" json:"out_medal"`
	SlotHit       int    `form:"slot_hit" json:"slot_hit"`
	GetShirbe     int    `form:"get_shirbe" json:"get_shirbe"`
	StartSlot     int    `form:"start_slot" json:"start_slot"`
	ShirbeBuy300  int    `form:"shirbe_buy300" json:"shirbe_buy300"`
	Medal1        int    `form:"medal_1" json:"medal_1"`
	Medal2        int    `form:"medal_2" json:"medal_2"`
	Medal3        int    `form:"medal_3" json:"medal_3"`
	Medal4        int    `form:"medal_4" json:"medal_4"`
	Medal5        int    `form:"medal_5" json:"medal_5"`
	RMedal        int    `form:"R_medal" json:"R_medal"`
	TotalPlayTime int    `form:"total_play_time" json:"total_play_time"`
	Fever         int    `form:"fever" json:"fever"`

	// Sig HMAC-SHA256署名（順序固定・user_id込みで生成）
	Sig              string `form:"sig" json:"sig"`
	MaxChainItem     *int   `form:"max_chain_item,omitempty" json:"max_chain_item,omitempty"`
	MaxChainOrange   *int   `form:"max_chain_orange,omitempty" json:"max_chain_orange,omitempty"`
	MaxChainRainbow  *int   `form:"max_chain_rainbow,omitempty" json:"max_chain_rainbow,omitempty"`
	SugorokuSteps    *int   `form:"sugoroku_steps,omitempty" json:"sugoroku_steps,omitempty"`
	Jackpots         *int   `form:"jackpots,omitempty" json:"jackpots,omitempty"`
	MaxJackpotWin    *int   `form:"max_jackpot_win,omitempty" json:"max_jackpot_win,omitempty"`
	MaxTotalJackpot  *int   `form:"max_total_jackpot,omitempty" json:"max_total_jackpot,omitempty"`
	MaxTotalUltimate *int   `form:"max_total_ultimate,omitempty" json:"max_total_ultimate,omitempty"`
}

// GetRankingsParams defines parameters for GetRankings.
type GetRankingsParams struct {
	Sort  *GetRankingsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
	Limit *int                   `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetRankingsParamsSort defines parameters for GetRankings.
type GetRankingsParamsSort string

// GetV2DataParams defines parameters for GetV2Data.
type GetV2DataParams struct {
	// Data URL エンコード済み JSON セーブデータ
	Data   string `form:"data" json:"data"`
	UserId string `form:"user_id" json:"user_id"`
	Sig    string `form:"sig" json:"sig"`
}

// GetV3DataParams defines parameters for GetV3Data.
type GetV3DataParams struct {
	// Data URL エンコード済み JSON セーブデータ
	Data   string `form:"data" json:"data"`
	UserId string `form:"user_id" json:"user_id"`
	Sig    string `form:"sig" json:"sig"`
}

// GetV3UsersUserIdDataParams defines parameters for GetV3UsersUserIdData.
type GetV3UsersUserIdDataParams struct {
	// Sig HMAC-SHA256 署名
	Sig string `form:"sig" json:"sig"`
}

// GetV4DataParams defines parameters for GetV4Data.
type GetV4DataParams struct {
	// Data URL エンコード済み JSON セーブデータ
	Data   string `form:"data" json:"data"`
	UserId string `form:"user_id" json:"user_id"`
	Sig    string `form:"sig" json:"sig"`
}

// GetV4UsersUserIdDataParams defines parameters for GetV4UsersUserIdData.
type GetV4UsersUserIdDataParams struct {
	// Sig HMAC-SHA256 署名
	Sig string `form:"sig" json:"sig"`
}
